"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os \
$directory \
$git_branch \
$git_status \
$fill \
$c \
$lua \
$rust \
$ruby \
$golang \
$nodejs \
$java \
$python \
$conda \
$cmd_duration \
$time \
$line_break$character"""


[os]
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""


[directory]
truncation_length = 0 
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# [module.git]          # this was causing the shell startup error
# disabled = false
# format = "$all"
# style = "bold red"

[git_branch]
symbol = "  "

[git_status]
conflicted = '🏳 ${count}'
ahead = '🏎💨 ${count}'
behind = '😰 ${count}'
diverged = '😵 ${count}'
up_to_date = '✓'
untracked = '🤷 ${count}'
stashed = '📦 ${count}'
modified = '📝 ${count}'
staged = '[++\\($count\\)](green)'
renamed = '👅 ${count}'
deleted = '🗑 ${count}'

[fill]
symbol = ' '

[nodejs]
symbol = " "
style = 'cyan'
format = '[$symbol($version )]($style)'

[c]
symbol = " "
style = 'white'
format = '[$symbol($version )]($style)'

[lua]
symbol = " "
style = 'blue'
format = '[$symbol($version )]($style)'

[rust]
symbol = " "
style = 'purple'
format = '[$symbol($version )]($style)'

[ruby]
symbol = " "
style = 'red'
format = '[$symbol($version )]($style)'

[golang]
symbol = " "
style = 'green'
format = '[$symbol($version )]($style)'

[java]
symbol = " "
style = 'blue'
format = '[$symbol($version )]($style)'

[python]
style = 'yellow'
symbol = ' '
pyenv_prefix = ''
# pyenv_version_name = true
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'

[time]
disabled = false
use_12hr = true
time_format = "%I:%M%P"
format = ' [$time]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
# vimcmd_symbol = '[V](bold green) '
